/**
* determine if a field is in a valid state
* meta(object): the meta data on a field generated by redux-form
*/
const getValidationState = (meta) => {
  if (meta.touched) {
    if (meta.error) {
      return 'error'
    } else if (meta.warning) {
      return 'warning'
    } else {
      return null
    }
  } else {
    return null
  }
}

export {getValidationState}